---

- name: Install dependencies for Ansible apt* modules
  command: apt-get -y install python-apt
  args:
    warn: no
  register: preconf_apt_dependencies_installed
  changed_when: "'is already the newest version' not in preconf_apt_dependencies_installed.stdout"

- name: Update and then safe upgrade installed packages
  apt:
    update_cache=yes
    cache_valid_time=3600
    upgrade=yes

# This is "standard system utilities" metapackage.
# @see sudo tasksel --task-package standard
- name: Install ubuntu standard utilities
  apt:
    pkg=ubuntu-standard
    install_recommends=yes

- name: Installing intel-microcode package for processors microcode updates
  apt: pkg=intel-microcode

- name: Installing zram (formely compcache)
  apt: pkg=zram-config

- name: Installing useful utilities
  apt: pkg={{ item }}
  with_items: "{{ preconf.utilities }}"

- name: Remove apt outdated caches and packages
  apt:
    autoclean: yes
    autoremove: yes

- name: Apply sysctl settings
  sysctl:
    name={{ item.key }}
    value={{ item.value }}
  with_dict: "{{ preconf.sysctl }}"

# The hostname service runs hostname -b -F /etc/hostname (see /etc/init/hostname.conf), which exits after setting
# the hostname, so it doesn't continue running. The following is not working on Ubuntu 16.04 Xenial:
# sudo service hostname restart
- name: Apply hostname
  hostname:
    name={{ preconf.hostname.hostname }}
  when: preconf.hostname.apply

- name: Apply FQDN hostname to /etc/hosts and others hosts parameters
  template:
    src=hosts.j2
    dest=/etc/hosts
    owner=root
    group=root
    mode=0644
  when: preconf.hostname.apply
