- name: Update and then safe upgrade installed packages
  apt:
    update_cache=yes
    upgrade=yes

- name: Installing useful utilities
  apt: pkg={{ item }}
  with_items: "{{ preconf.utilities }}"

- name: Apply sysctl settings
  sysctl:
    name={{ item.key }}
    value={{ item.value }}
  with_dict: "{{ preconf.sysctl }}"

# The hostname service runs hostname -b -F /etc/hostname (see /etc/init/hostname.conf), which exits after setting
# the hostname, so it doesn't continue running. The following is not working on Ubuntu 16.04 Xenial:
# sudo service hostname restart
- name: Apply hostname
  hostname:
    name={{ preconf.hostname.hostname }}
  when: "{{ preconf.hostname.apply }}"

- name: Apply FQDN hostname to /etc/hosts and others hosts parameters
  template:
    src=hosts.j2
    dest=/etc/hosts
    owner=root
    group=root
    mode=0644
  when: "{{ preconf.hostname.apply }}"
