---

preconf:
  apt_keys:
    nodesource:
      id: 1655A0AB68576280
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: ignored
    sbt:
      id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
      url: hkp://keyserver.ubuntu.com:80
      state: ignored

  repositories:
    nodejs_10_xenial:
      repository: deb https://deb.nodesource.com/node_10.x xenial main
      filename: nodesource
      state: ignored
    nodejs_10_xenial_src:
      repository: deb-src https://deb.nodesource.com/node_10.x xenial main
      filename: nodesource
      state: ignored
    sbt:
      repository: deb https://dl.bintray.com/sbt/debian /
      filename: sbt
      state: ignored

  hostname:
    apply: no
    hostname: example
    fqdn: example.org
    ipv4: 127.0.1.1
  hosts: ''
  sysctl: {}
    # Next is Dropbox and PhpStorm issue:
    #
    # Dropbox:
    # echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p
    #
    # PhpStorm:
    # http://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
    # 1. In file "/etc/sysctl.conf" change/add row: "fs.inotify.max_user_watches = 524288"
    # 2. Then "sudo sysctl -p" to apply changes immediately
#    fs.inotify.max_user_watches: 524288
  suggested:
    - apachetop
    - aptitude
    - atop
    - dar
    - dstat
    - fortunes-ubuntu-server
    - git-svn
    - hddtemp
    - mytop
    - lynx
    - p7zip
    - rar
    - subversion
    # It seems this package has no sense in Ubuntu 16.04 Xenial Xerus
#    - sysv-rc-conf
    - vim
    # visitors is not available in Ubuntu 16.04 Xenial Xerus
#    - visitors
  utilities:
    - acl
    - apt-file
    - bc
    - ccze
    - curl
    - facter
    - fail2ban
    - grc
    - htop
    - iftop
    - ioping
    - iotop
    - itop
    - lm-sensors
    - lsscsi
    - mc
    - mcelog
    - ncdu
    - ncurses-term
    - nethogs
    - nmap
    - powertop
    - pwgen
    - python-software-properties
    - rsnapshot
    - rsync
    - smartmontools
    - sudo
    - sysstat
    - tcpdump
    - tmux
    - traceroute
    - tree
    - wget
