---

preconf:
  hostname:
    apply: no
    hostname: example
    fqdn: example.org
    ipv4: 127.0.1.1
  hosts: ''
  sysctl:
    # Next is Dropbox and PhpStorm issue:
    #
    # Dropbox:
    # echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p
    #
    # PhpStorm:
    # http://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
    # 1. In file "/etc/sysctl.conf" change/add row: "fs.inotify.max_user_watches = 524288"
    # 2. Then "sudo sysctl -p" to apply changes immediately
    fs.inotify.max_user_watches: 524288
  utilities:
    - acl
    - apachetop
    - aptitude
    - atop
    - bc
    - ccze
    - curl
    - dar
    - dstat
    - facter
    - fortunes-ubuntu-server
    - git-svn
    - grc
    - htop
    - iftop
    - iotop
    - itop
    - lynx
    - mcelog
    - mytop
    - ncurses-term
    - nethogs
    - nmap
    - p7zip
    - powertop
    - pwgen
    - python-software-properties
    - rar
    - smartmontools
    - subversion
    - sudo
    - sysstat
    - sysv-rc-conf
    - tcpdump
    - tmux
    - traceroute
    - tree
    - vim
# visitors is not available in Ubuntu 16.04 Xenial
#    - visitors
    - wget
