---

preconf:

  # Packages to remove or purge. Executed first. The `state` or `purge` field are not required.
  # You can use `state: ignored` for excluding some packages from removal. Purge is `False` by default.
  packages_remove:
    some_example_pkg:
      purge: True
      state: ignored

  package_sets:
    common:
      - acl
      - curl
      - htop
      - mc
      - ncdu
      - nmap
      - rsync
      - screen
      - sudo
      - zram-config
    openjdk-r:
      - openjdk-11-jdk
    server:
      - fail2ban
    suggested:
      - apachetop
      - aptitude
      - atop
      - dar
      - dstat
      - fortunes-ubuntu-server
      - git-svn
      # This package is not available in Ubuntu 18.04 Bionic Beaver, in spite of kernel use mcelog legacy
#      - mcelog
      - mytop
      - lynx
      - p7zip
      # This package is not available in Ubuntu 18.04 Bionic Beaver
#      - python-software-properties
      - rar
      - subversion
      # It seems this package has no sense in Ubuntu 16.04 Xenial Xerus
  #    - sysv-rc-conf
      - vim
      # visitors is not available in Ubuntu 16.04 Xenial Xerus
  #    - visitors

  package_sets_install:
    - common

  grub:
    - regexp: "^[#]*GRUB_TIMEOUT="
      line: 'GRUB_TIMEOUT=2'
    - regexp: "^[#]*GRUB_RECORDFAIL_TIMEOUT="
      line: 'GRUB_RECORDFAIL_TIMEOUT=2'

  systemd:
    services:
      # sleep.target suspend.target hibernate.target hybrid-sleep.target are masked for disabling
      # suspend and hibernation. Commands ignored by default, enable it in your appropriate host group.
      'sleep.target':
        masked: yes
        ignored: yes
      'suspend.target':
        masked: yes
        ignored: yes
      'hibernate.target':
        masked: yes
        ignored: yes
      'hybrid-sleep.target':
        masked: yes
        ignored: yes

  lid:
    switchignore: no

  hostname:
    apply: no
    hostname: example
    fqdn: example.org
    ipv4: 127.0.1.1
  hosts: ''
  sysctl: {}
    # Next is Dropbox and PhpStorm issue:
    #
    # Dropbox:
    # echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p
    #
    # PhpStorm:
    # http://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
    # 1. In file "/etc/sysctl.conf" change/add row: "fs.inotify.max_user_watches = 524288"
    # 2. Then "sudo sysctl -p" to apply changes immediately
#    fs.inotify.max_user_watches: 524288
  utilities:
    - apt-file
    - bc
    - ccze
    - facter
    - fail2ban
    - grc
    - iftop
    - ioping
    - iotop
    - itop
    - lm-sensors
    - lsscsi
    - ncurses-term
    - nethogs
    - powertop
    - pwgen
    - rsnapshot
    - smartmontools
    - sysstat
    - tcpdump
    - tmux
    - traceroute
    - tree
    - wget
